export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_OTP_CODE = 'INVALID_OTP_CODE',
  HTTP_METHOD_NOT_ALLOWED = 'HTTP_METHOD_NOT_ALLOWED',
  CLOUD_WALLET_NOT_AUTHENTICATED = 'CLOUD_WALLET_NOT_AUTHENTICATED',
  JWT_EXPIRED_ERROR = 'JWT_EXPIRED_ERROR',
  COR_5 = 'COR-5',
  COR_17 = 'COR-17',
  CWA_4 = 'CWA-4',
}
