import Head from "next/head";
import React, { FC } from "react";

import { Container, Header, Typography } from "components";

const Home: FC = () => (
  <>
    <Head>
      <title>Developer Reputation App</title>
      <meta name="description" content="Generated by someone" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header title="Developer Reputation" />
    <Container>
      <Typography variant="p1">
        Welcome to the start of your developer reputation.
      </Typography>
    </Container>
  </>
);

export default Home;
