```plantuml
@startuml

User -> App : sign into Holder's wallet
App -> CW as "Cloud Wallet" : sign in
CW -> App : [Cloud Wallet access token]
App -> App : open "Profile Setup" page

App -> CW : fetch credentials
CW -> App : [credentials]
App -> App : filter credentials and find a GithubProfile VC

alt Holder doesn't have a GithubProfile VC yet

User -> App : connect Github profile
App -> GH as "Github" : authenticate with Github
GH -> App : [Github access token]
App -> GH as "Github" : fetch profile data
GH -> App : [profile data]
App -> CW : issue GithubProfile VC
CW -> App : (ok)

end

App -> App : open "Github profile" page

@enduml
```